In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix,ConfusionMatrixDisplay

df = pd.read_csv('disease_stage.csv')
df.head()

age        b1        b2        b3         b4  stage
0   29 -0.546507  1.081220 -1.972578   8.168842      0
1   35 -0.515717  6.465299 -3.663720  12.219401      1
2   35  0.297982  6.710920 -3.159595  10.055708      0
3   73  0.760905  7.574649 -2.055028  13.548206      0
4   50 -0.199529  5.941957 -3.226261  16.328148      1

In [7]:
x=df[['age','b1','b2','b3','b4']]
y=df['stage']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
model=LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=1000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print('Report:')
print(f'Accuracy:{accuracy_score(y_test,y_pred)}\n')
print(f'Marco_F1:{f1_score(y_test,y_pred,average="macro")}\n')
print(f'Weighted_f1:{f1_score(y_test,y_pred,average="weighted")}\n')
print(f'Confusion Matrix:\n{confusion_matrix(y_test,y_pred)}\n')

Report:
Accuracy:0.25

Marco_F1:0.23164874551971326

Weighted_f1:0.25556182795698923

Confusion Matrix:
[[7 6 3]
 [3 1 7]
 [5 6 2]]



c:\Users\kishore\AI WORKFORCE DAY 13\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
